project:
  type: website

website:
  title: "reproducibility-course"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: references.qmd
        text: References
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    bibliography: references.bib
    csl: apa-6th-edition.csl



