project:
  type: website
  output-dir: _site
  execute-dir: project
  preview: 
    port: 9999
    host: 127.0.0.1
    browser: true
    watch-inputs: true
    navigate: true

website:
  title: "Reproducibility Course"
  search: true
  repo-url: https://github.com/lnnrtwttkhn/reproducibility-course/
  repo-branch: main
  repo-actions: [issue, source]
  twitter-card: false
  site-url: https://lennartwittkuhn.com/reproducibility-course/
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: schedule.qmd
        text: Schedule  
      - href: references.qmd
        text: References
      - about.qmd
    right:
      - href: "{{< var links.nextcloud-url >}}"
        text: "{{< fa cloud-arrow-up >}} Files"
      - href: "{{< var links.repo-url >}}"
        text: "{{< fa brands github >}} Code"

format:
  html:
    theme: cosmo
    css: styles.css
    link-external-newwindow: true
    toc: true
    toc-depth: 3
    toc-title: "On this page"
    number-sections: false
    anchor-sections: true
    # layout (https://quarto.org/docs/reference/formats/html.html#layout):
    fig-cap-location: margin
    page-layout: full
    title-block-style: none
    # code (https://quarto.org/docs/reference/formats/html.html#code):
    code-fold: false
    code-overflow: wrap
    code-line-numbers: false
    code-copy: true
    code-link: false
    code-annotations: hover
    code-tools: false
    highlight-style: monokai
    # references:
    bibliography: references.bib
    csl: apa-6th-edition.csl
    citations-hover: true
    # footnotes:
    footnotes-hover: true
    # includes:
    include-after-body: plausible.html
